### ISSUE TITLE
submodule

### ISSUE THREAD

**Issue by wolfcod** [aar10n/osdev#3]
Hi, I was trying to clone & build your project, but both submodule (lib/fmt, third-party/musl) are referencing a wrong commit.

**Comment by calligraf0** [comment]
In the Makefile, under the `setup` action, change: `git submodule --init --recursive` to `git submodule update --force  --remote --init --recursive`. Worked for me :)

**Comment by aar10n** [comment]
Sorry for the delay. Yeah, I messed up with the submodules and for musl libc I should be targeting a fork not upstream. I also decided to just include the slightly modified fmt_c in tree. I'm in the process of a rather large rewrite of core process/thread and scheduling code. I'll include the fixes for both these issues when I get around to finishing that. 

With that said, it's not really in a state to be built right now anyways so even with this fixed you would soon run into issues trying to run it.

**Comment by wolfcod** [comment]
Hi, thanks for the answer. I'll try to figure out how to build.
